menu:
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'projects', url: '/projects'}

courses:
- {name: 'Computer System', url: 'computer-system'}
- {name: 'Computer Vision', url: 'computer-vision'}
- {name: 'Logic Circuit Design', url: 'logic-circuit-design'}

projects:
- {name: 'Software Engineering', url: 'software-engineering'}


social:
- {icon: 'github', link: 'https://github.com/JiwooHong01'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jiwoo-hong-20694132b/'}

